run:
	./build/sampleDetect -e /home/SENSETIME/yangchengwei/900G/coding/github/spaceX/libtorch/model/yolov8n.engine


dump-engine:
	./build/sampleDetect -m /home/SENSETIME/yangchengwei/900G/coding/github/spaceX/libtorch/model/yolov8n.onnx
